### ISSUE TITLE
Project deletion sometimes fails with 502 Proxy Error

### ISSUE THREAD

**Issue by sgaspari** [GroupePSA/sonarqube-cleanup-cli#19]
SonarQube projects cleanup process may fail with following exception:
```
Deleting project: com.company.something:some-project:some-branch
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported status code: 502 Proxy Error / Content: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/api/projects/delete">POST&nbsp;/api/projects/delete</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>

        at org.psa.sonarqube.cleanup.rest.AbstractClient.call(AbstractClient.java:97)
        at org.psa.sonarqube.cleanup.rest.AbstractClient.post(AbstractClient.java:53)
        at org.psa.sonarqube.cleanup.rest.SonarQubeClient.deleteProject(SonarQubeClient.java:63)
        at org.psa.sonarqube.cleanup.SonarQubeCleanupCli.main(SonarQubeCleanupCli.java:76)
```

When process is played again, it continues with next projects deletion, and we can see in SonarQube that the project is correctly deleted, despite the error.
Moreover a dry run execution has never failed with this error.

FYI the command was launched in a Git Bash CLI where no HTTP/HTTPS proxy exists, only the follwing sysenv: `no_proxy=.company.com,localhost`

**Comment by axel3rd** [comment]
Is it possible to reproduce error at next launch running [Wireshark](https://www.wireshark.org/) in // ? To analyse TCP content. 
Because currently root cause is not trivial 😢

**Comment by axel3rd** [comment]
@sgaspari : The error comes from proxy (Apache, ...). Is it possible to execute program with native SonarQube port (9000 by default), to have the original error from SonarQube.

**Comment by sgaspari** [comment]
Next executions will be done with native SonarQube port added in the SonarQube server URL.

**Comment by axel3rd** [comment]
@sgaspari : Did you wan't a try on last SNAPSHOT or 1.1 release direct ?
