### ISSUE TITLE
OSS license

### ISSUE THREAD

**Issue by axel3rd** [GroupePSA/sonarqube-cleanup-cli#2]
An OSS license should be chosen. 

@adrienlauer : Any advice is welcome 😃 😗 !

**Comment by adrienlauer** [comment]
As discussed together, I think a simple MIT license for this kind of tool is the way to go. Straightforward and very open.

**Comment by axel3rd** [comment]
@adrienlauer : Many thanks !

**Comment by axel3rd** [comment]
`bintray-descriptor.json` content should be fixed about *licenses* tag.

**Comment by axel3rd** [comment]
Todo:
- `LICENSE.txt` file creation (https://choosealicense.com/licenses/mit/)
- Fix `bintray-descriptor.json`
- Update GitHub settings license repository
