### ISSUE TITLE
Please publish releases of this cli

### ISSUE THREAD

**Issue by Bjego** [GroupePSA/sonarqube-cleanup-cli#40]
@axel3rd I think your project could be interesting for our admins. Could you please publish the releases of you tool in github? So that an admin just needs to download the latest release of this cli?

**Comment by axel3rd** [comment]
@Bjego : This is already the case (zip downloadable), see **Download** button at top of repository homepage.

![image](https://user-images.githubusercontent.com/2912441/105145494-1cb95380-5aff-11eb-9867-dc8834301cca.png)

**Comment by Bjego** [comment]
Cool , we can close this then . Thanks!
