### ISSUE TITLE
Is there a flag where I can set the max age of projects?

### ISSUE THREAD

**Issue by Bjego** [GroupePSA/sonarqube-cleanup-cli#41]
I think it would be great, if I could define a max age (last scan date) in days of my projects and all projects older than that date, will be deleted as well.
This can free up many ressources and also allows people to revisit their licenses.

I could imagine such a parameter:
```
sonarqube-cleanup-cli.[sh|bat] -h http://sonarqube.company.com -l adminUser -p foobar -maxAge 365
```

And then the cli should be able to find and delete all projects older then 365 days.

**Comment by axel3rd** [comment]
IMO this option is not compatible with *thresholdCoeff*/*numberLocAdd* options ; it is a second orientation if this batch.

The specification for this option could be:

```
-a,--age <arg>     The age (in days) for which deleting the old projects (default: -1 => not used ; or sysenv 'SONAR_CLEANUP_MAX_AGE'). This option overrides 'thresholdCoeff /numberLocAdd' options.
```

**Comment by Bjego** [comment]
Yep - I thought this age option is more a tool to reevaluate your license size. After deleting old projects you may free up pretty much lines of code and you may can resize your license size.

I'm pretty open to any kind of argument. I like your suggestion and I'd love the opporunity to free up quite a lot of lines of code witch just one cli call :)
